{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fission.wear.glasses",
    "module": "sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.0.aar",
          "url": "sdk-1.0.0.aar",
          "size": 1471137,
          "sha512": "6ba3bba6a3094d72d402757297c5118f0c230394b428f1aa37839c6984c479ebb705c60ec4c7990bd5361bd917d8f25ebea069a88b77d942cea8cd407c8ee1cf",
          "sha256": "2a2006d1c479a50794882c723857896ab9db8ab789aa5b94ffb37e00693d0c0f",
          "sha1": "b400d2c7274e937ff1269cd244967adfe20eff68",
          "md5": "92d734a489d739cde8f20565782903d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-websockets",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-1.0.0.aar",
          "url": "sdk-1.0.0.aar",
          "size": 1471137,
          "sha512": "6ba3bba6a3094d72d402757297c5118f0c230394b428f1aa37839c6984c479ebb705c60ec4c7990bd5361bd917d8f25ebea069a88b77d942cea8cd407c8ee1cf",
          "sha256": "2a2006d1c479a50794882c723857896ab9db8ab789aa5b94ffb37e00693d0c0f",
          "sha1": "b400d2c7274e937ff1269cd244967adfe20eff68",
          "md5": "92d734a489d739cde8f20565782903d2"
        }
      ]
    }
  ]
}
