{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fission.wear.glasses",
    "module": "classic-bt",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.wandersnail",
          "module": "commons-android",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "classic-bt-1.0.0.aar",
          "url": "classic-bt-1.0.0.aar",
          "size": 41576,
          "sha512": "dcdca6440f6cdd664ee86b905b9627c4f98643936d80276006156460036f54c33062b106a52854aa518049350cf9a1425d0d808fb512ada93b9707b2a770b9f5",
          "sha256": "1af5168854b3b5eba5af014965d1a7b227b4cb317fda74e0874e58574e105014",
          "sha1": "dac93454491542ea50a0ffa514e73f4f9a239695",
          "md5": "2e5756b913c3f0e6f83a716e61147fdf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.wandersnail",
          "module": "commons-android",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "classic-bt-1.0.0.aar",
          "url": "classic-bt-1.0.0.aar",
          "size": 41576,
          "sha512": "dcdca6440f6cdd664ee86b905b9627c4f98643936d80276006156460036f54c33062b106a52854aa518049350cf9a1425d0d808fb512ada93b9707b2a770b9f5",
          "sha256": "1af5168854b3b5eba5af014965d1a7b227b4cb317fda74e0874e58574e105014",
          "sha1": "dac93454491542ea50a0ffa514e73f4f9a239695",
          "md5": "2e5756b913c3f0e6f83a716e61147fdf"
        }
      ]
    }
  ]
}
